version: '3'
services:
  backend:
    image: node:18
    working_dir: /app
    volumes:
      - ./:/app
    command: bash -c "cd /app && npm install && npm run dev:backend"
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development

  frontend:
    image: node:18
    working_dir: /app
    volumes:
      - ./:/app
    command: bash -c "cd /app/src/frontend && npm install && npm run serve"
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development

volumes:
  node_modules: