version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pubsignage-app
    restart: unless-stopped
    ports:
      - "3000:3000"  # Frontend Vite dev server
      - "8080:8080"  # Backend API server
    volumes:
      - .:/app
      - /app/node_modules
      - /app/src/frontend/node_modules
      - /app/src/backend/node_modules
      - ./data:/app/data
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true  # Enable hot reload on mounted volumes
    networks:
      - pubsignage-network

  # SQLite database management UI (optional)
  adminer:
    image: adminer:latest
    container_name: pubsignage-adminer
    restart: unless-stopped
    ports:
      - "8081:8080"
    environment:
      - ADMINER_DEFAULT_SERVER=sqlite
    volumes:
      - ./data/db:/var/www/html/data
    networks:
      - pubsignage-network

networks:
  pubsignage-network:
    driver: bridge